# Day-4-of-Java-Problem-Solving
On the day 3 I learn about how to demonstrate various exception handling mechanisms and file operations. Each program highlights a specific use case of exceptions in Java, including both built-in and user-defined exceptions.
The problems I solved in this repo are following:
1. Write a java program that performs division of two numbers, where the denominator 
is zero, and handle the exception using try-catch to prevent program termination. Also, 
print a message after the exception handling block. 
2. Demonstrate a Java program named ExcepTest3 that handles a NullPointerException 
using try-catch-finally blocks. 
In this program, initialize a String variable with null and attempt to access its length 
inside the try block to deliberately cause the exception. Handle the exception in the 
catch block, and in the finally block, assign a valid value to the String and print it. 
3. Demonstrate a Java program named WriteData_Demo that writes data to a text file 
using FileWriter. 
In this program, create a file named file.txt and write some sample text to it inside the 
try block. Handle possible IOException using a catch block, and ensure the file writer 
resource is closed properly inside the finally block. 
4. Demonstrate a Java program that defines a user-defined exception class 
AgeNotValidException to validate the age for voting. If age is less than 18, throw the 
exception. 
5. Demonstrate a Java program with the class name BankDemo to simulate a bank 
transaction scenario. Define a user-defined exception class named 
InsufficientFundsException which is thrown when the withdrawal amount exceeds 
the account balance.
